# Generated by Django 5.2.6 on 2026-09-22 15:13

import clips.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0002_alter_camera_options_alter_server_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('file', models.FileField(upload_to=clips.models.clip_upload_path, verbose_name='ファイル')),
                ('media_type', models.CharField(choices=[('image', '静止画'), ('video', '動画')], default='image', max_length=10, verbose_name='種別')),
                ('taken_at', models.DateTimeField(verbose_name='映像取得日時')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='cameras.camera', verbose_name='カメラ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to=settings.AUTH_USER_MODEL, verbose_name='保存したユーザー')),
            ],
            options={
                'verbose_name': 'クリップ',
                'verbose_name_plural': 'クリップ',
                'db_table': 'clips',
                'ordering': ('-taken_at',),
            },
        ),
    ]
