# Generated by Django 5.2.6 on 2026-09-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='長さ(秒)'),
        ),
    ]
