# Generated by Django 5.2.6 on 2026-09-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='サーバー名')),
                ('address', models.CharField(max_length=255, verbose_name='接続先アドレス')),
                ('line', models.CharField(max_length=100, verbose_name='製造ライン名')),
            ],
            options={
                'verbose_name': 'サーバー',
                'verbose_name_plural': 'サーバー',
                'db_table': 'servers',
                'ordering': ('line', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カメラ名')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cameras.server', verbose_name='サーバー')),
            ],
            options={
                'verbose_name': 'カメラ',
                'verbose_name_plural': 'カメラ',
                'db_table': 'cameras',
                'ordering': ('server', 'name'),
            },
        ),
    ]
