# Generated by Django 5.2.6 on 2026-09-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ('server', 'id'), 'verbose_name': 'カメラ', 'verbose_name_plural': 'カメラ'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('id',), 'verbose_name': 'サーバー', 'verbose_name_plural': 'サーバー'},
        ),
    ]
